// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var Variants$LearningReason = require("./experimenting/Variants.bs.js");

console.log("Hello, BuckleScript and Reason!");

Variants$LearningReason.run(/* () */0);

/*  Not a pure module */
