// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var TypedFun$LearningReason = require("./experimenting/TypedFun.bs.js");

console.log("Hello, BuckleScript and Reason!");

TypedFun$LearningReason.run(/* () */0);

/*  Not a pure module */
